
title: calamixys blog
author: Calamixy
main
email: calamixy@wearehackerone.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog, user! Announcements about my services will be made here. Catch all of the updates here!

# social links
twitter_username: DevCalamixy # DO NOT include the @ character, or else the build will fail!
github_username:  Calamixy # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
