title: calamixy's blog
author: Calamixy
email: calamixy@wearehackerone.com
description: > # this means to ignore newlines until "baseurl:"
  Hi there! Welcome to my blog. You will catch all of my latest updates to my services here! Enjoy.

# social links
twitter_username: DevCalamixy # DO NOT include the @ character, or else the build will fail!
github_username:  Calamixy # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima